/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.Demo;

import br.unesp.rc.Dao.AuthDAO;
import br.unesp.rc.Dao.DenunciaDAO;
import br.unesp.rc.Dao.FabricaDAO;
import br.unesp.rc.Dao.FollowDAO;
import br.unesp.rc.Dao.TweetDAO;
import br.unesp.rc.Emocao.adicionarBase;
import br.unesp.rc.Model.Tweet;
import br.unesp.rc.Model.associacaoTwitter;
import br.unesp.rc.Model.Usuario;
import br.unesp.rc.Model.denunciaTweet;
import br.unesp.rc.Twitter.mostrarTweet;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import twitter4j.Status;
import twitter4j.TwitterException;

/**
 *
 * @author marco
 */
public class telaDenunciar extends javax.swing.JFrame {

    
    private ArrayList<String> followers;
    private ArrayList<String> listaTweet;
    private Usuario user;
   
    /**
     * Creates new form telaDenunciar
     */
    public telaDenunciar() {
        initComponents();
    }

    public telaDenunciar(Usuario user) throws SQLException, TwitterException, IOException {
        initComponents();
        this.user = user;
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo2.png")));
        this.setTitle("Denuncie um Tweet, " + user.getNome());
        
        FollowDAO fd = FabricaDAO.getFollowDAO();
        followers = fd.getFollowers(this.user);
        
        DefaultTableModel model = (DefaultTableModel) tabelaTweet.getModel();
        
        for(String f : followers){
            Usuario follow = new Usuario();
            follow.setNome(f);
           
            TweetDAO td = FabricaDAO.getTweetDAO();
            listaTweet = td.consultarTweet(follow);
        
             if(listaTweet != null){
                for (String tweet : listaTweet){
                    mostrarTweet twt = new mostrarTweet();
                    Status status = twt.buscarTweet(tweet,this.user.getAt());
                    model.addRow(new Object[]{status.getText(),follow.getNome()});
                }
            }
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDenunciar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTweet = new javax.swing.JTable();
        btnDenunciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDenunciar.setText("Denunciar Tweet");

        tabelaTweet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mensagem", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTweet);

        btnDenunciar.setText("Denunciar");
        btnDenunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenunciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDenunciar)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDenunciar)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDenunciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(btnDenunciar)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDenunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenunciarActionPerformed
        // TODO add your handling code here:
        Usuario user_denunciar = new Usuario();
        Tweet tweet = new Tweet();
        denunciaTweet dt = new denunciaTweet();
        adicionarBase addbase = new adicionarBase();
        
        tweet.setIdMensagem(Long.parseLong(listaTweet.get(tabelaTweet.getSelectedRow())));
        dt.setMotivo("Mensagem Ofensiva");
        tweet.setDenunciaTweet(dt);
        associacaoTwitter atdenunciar = new associacaoTwitter();
        
        user_denunciar.setNome(tabelaTweet.getValueAt(tabelaTweet.getSelectedRow(),1).toString());
        System.out.println(tabelaTweet.getValueAt(tabelaTweet.getSelectedRow(),1));
        DefaultTableModel model = (DefaultTableModel) tabelaTweet.getModel();
        
        TweetDAO tdao = FabricaDAO.getTweetDAO();
        AuthDAO auth = FabricaDAO.getOAuthDAO();
        DenunciaDAO ddao = FabricaDAO.getDenunciaDAO();
        
        try {
            atdenunciar = auth.getAuth(user_denunciar);
            user_denunciar.setAt(atdenunciar);
            addbase.append(tabelaTweet.getValueAt(tabelaTweet.getSelectedRow(),0).toString());
            tdao.updateCategoria(tweet);
            ddao.addDenuncia(tweet);
            JOptionPane.showMessageDialog(this, "Tweet denunciado");
        } catch (SQLException ex) {
            Logger.getLogger(telaDenunciar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(telaDenunciar.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnDenunciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDenunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDenunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDenunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDenunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDenunciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDenunciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDenunciar;
    private javax.swing.JTable tabelaTweet;
    // End of variables declaration//GEN-END:variables
}
