/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.Demo;

import br.unesp.rc.Dao.FabricaDAO;
import br.unesp.rc.Dao.TweetDAO;
import br.unesp.rc.Model.associacaoTwitter;
import br.unesp.rc.Model.Usuario;
import br.unesp.rc.Twitter.mostrarTweet;
import br.unesp.rc.Twitter.removerTweet;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import twitter4j.Status;
import twitter4j.TwitterException;

/**
 *
 * @author Raphael
 */
public class telaRemoverTweet extends javax.swing.JFrame {

    /**
     * Creates new form telaRemoverTweet
     */
    
     ArrayList<String> listaTweet = new ArrayList<String>();
     private Usuario user;
     
    public telaRemoverTweet() {
        initComponents();
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo2.png")));
    }
     public telaRemoverTweet(Usuario user) throws SQLException, TwitterException {
         this.user = user;
        initComponents();
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo2.png")));
        this.setTitle("Remover Tweet");
        DefaultTableModel model = (DefaultTableModel) tabelaTweet.getModel();
       
        
        TweetDAO td = FabricaDAO.getTweetDAO();
        listaTweet = td.consultarTweet(user);
        
        if(listaTweet != null){
            for (String tweet : listaTweet){
                mostrarTweet twt = new mostrarTweet();
                Status status = twt.buscarTweet(tweet,user.getAt());
                model.addRow(new Object[]{status.getText()});
                System.out.println(status.getText());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTweet = new javax.swing.JTable();
        btnExcluirTweet = new javax.swing.JButton();
        lblRemover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaTweet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTweet);

        btnExcluirTweet.setText("Excluir");
        btnExcluirTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTweetActionPerformed(evt);
            }
        });

        lblRemover.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRemover.setText("O que deseja excluir ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRemover)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(btnExcluirTweet)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRemover)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btnExcluirTweet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTweetActionPerformed
        // TODO add your handling code here:
        //System.out.println(tabelaTweet.getValueAt(tabelaTweet.getSelectedRow(),0).toString());
       System.out.println(listaTweet.get(tabelaTweet.getSelectedRow()));
       DefaultTableModel model = (DefaultTableModel) tabelaTweet.getModel();
       
       TweetDAO tdao = FabricaDAO.getTweetDAO();
       removerTweet rt = new removerTweet();
       
         try {
             tdao.removerTweet(listaTweet.get(tabelaTweet.getSelectedRow()));
             rt.removerTweet(listaTweet.get(tabelaTweet.getSelectedRow()), user.getAt());
             model.removeRow(tabelaTweet.getSelectedRow());
         } catch (SQLException ex) {
             Logger.getLogger(telaRemoverTweet.class.getName()).log(Level.SEVERE, null, ex);
         } catch (TwitterException ex) {
             Logger.getLogger(telaRemoverTweet.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnExcluirTweetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaRemoverTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaRemoverTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaRemoverTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaRemoverTweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaRemoverTweet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirTweet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JTable tabelaTweet;
    // End of variables declaration//GEN-END:variables
}
