/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.Demo;

import br.unesp.rc.Dao.FabricaDAO;
import br.unesp.rc.Dao.FollowDAO;
import br.unesp.rc.Dao.UsuarioDAO;
import br.unesp.rc.Model.associacaoTwitter;
import br.unesp.rc.Model.Usuario;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import twitter4j.TwitterException;

/**
 *
 * @author marco
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    private Usuario userform;
    
     public telaPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo2.png")));
    }
    
    public telaPrincipal(Usuario user) {
        userform = user;
        initComponents();
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo2.png")));
        this.setTitle("Bem Vindo " + userform.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEscrever = new javax.swing.JMenuItem();
        menuRemover = new javax.swing.JMenuItem();
        menuTweet = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        menuConsultarTweets = new javax.swing.JMenuItem();
        menuConsultarCategoria = new javax.swing.JMenu();
        btnTodosAmigos = new javax.swing.JMenuItem();
        btnJovem = new javax.swing.JMenuItem();
        btnAdulto = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        btnDados = new javax.swing.JMenuItem();
        btnCategoria = new javax.swing.JMenuItem();
        btnResponsavel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal_Twitter.png"))); // NOI18N

        jMenu1.setText("Tweet");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        menuEscrever.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuEscrever.setText("Escrever um Tweet");
        menuEscrever.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEscreverMouseClicked(evt);
            }
        });
        menuEscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEscreverActionPerformed(evt);
            }
        });
        jMenu1.add(menuEscrever);

        menuRemover.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuRemover.setText("Remover um Tweet");
        menuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoverActionPerformed(evt);
            }
        });
        jMenu1.add(menuRemover);

        menuTweet.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuTweet.setText("Denunciar um Tweet");
        menuTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTweetActionPerformed(evt);
            }
        });
        jMenu1.add(menuTweet);

        jMenuBar1.add(jMenu1);

        menuConsultar.setText("Consultar");
        menuConsultar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        menuConsultarTweets.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuConsultarTweets.setText("Consultar meus tweets");
        menuConsultarTweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarTweetsActionPerformed(evt);
            }
        });
        menuConsultar.add(menuConsultarTweets);

        menuConsultarCategoria.setText("Consultar meus amigos pela categoria");
        menuConsultarCategoria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnTodosAmigos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTodosAmigos.setText("Todos meus amigos");
        btnTodosAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosAmigosActionPerformed(evt);
            }
        });
        menuConsultarCategoria.add(btnTodosAmigos);

        btnJovem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnJovem.setText("Jovens");
        btnJovem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJovemActionPerformed(evt);
            }
        });
        menuConsultarCategoria.add(btnJovem);

        btnAdulto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAdulto.setText("Adultos");
        btnAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdultoActionPerformed(evt);
            }
        });
        menuConsultarCategoria.add(btnAdulto);

        menuConsultar.add(menuConsultarCategoria);

        jMenuBar1.add(menuConsultar);

        menuEditar.setText("Meus Dados");
        menuEditar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnDados.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnDados.setText("Usuário");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        menuEditar.add(btnDados);

        btnCategoria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCategoria.setText("Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        menuEditar.add(btnCategoria);

        btnResponsavel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnResponsavel.setText("Responsável");
        btnResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsavelActionPerformed(evt);
            }
        });
        menuEditar.add(btnResponsavel);

        jMenuBar1.add(menuEditar);

        jMenu3.setText("Sair");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEscreverActionPerformed
        // TODO add your handling code here:
        
         new telaEscreverTweet(userform).setVisible(true);
    }//GEN-LAST:event_menuEscreverActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:     
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void menuEscreverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEscreverMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_menuEscreverMouseClicked

    private void menuConsultarTweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarTweetsActionPerformed
        try {
            // TODO add your handling code here:
            new telaConsultarTweet(userform).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TwitterException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuConsultarTweetsActionPerformed

    private void menuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoverActionPerformed
        try {
            // TODO add your handling code here:
            new telaRemoverTweet(userform).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TwitterException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRemoverActionPerformed

    private void menuTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTweetActionPerformed
        
        try {
            // TODO add your handling code here:
            new telaDenunciar(userform).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TwitterException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_menuTweetActionPerformed

    private void btnTodosAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosAmigosActionPerformed
        
        try {
            new telaConsultarAmigos(userform).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTodosAmigosActionPerformed

    private void btnJovemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJovemActionPerformed
        // TODO add your handling code here:
        
        FollowDAO fwdao = FabricaDAO.getFollowDAO();
        ArrayList<String> followers = new ArrayList<String>();
        try {
            followers = fwdao.getFollowersCategoria(userform, "Jovem");
            for(String e : followers) {System.out.println(e);}
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnJovemActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        UsuarioDAO userdao = FabricaDAO.getUsuarioDAO();
        String result = null;
        try {
            result = userdao.getCategoria(userform);
            JOptionPane.showMessageDialog(this,"Categoria: " + result);
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsavelActionPerformed
        // TODO add your handling code here:
        
        UsuarioDAO userdao = FabricaDAO.getUsuarioDAO();
        String result = null;
        try {
            result = userdao.getResponsavel(userform);
            if(result == null){
            JOptionPane.showMessageDialog(this, "Você é o responsável por sua conta");
            }
            else{
            JOptionPane.showMessageDialog(this,"Responsável: " + result);
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnResponsavelActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        // TODO add your handling code here:
        
        UsuarioDAO userdao = FabricaDAO.getUsuarioDAO();
        ArrayList<String> dados = new ArrayList<String>();
        try {
            dados = userdao.getDados(userform);
            JOptionPane.showMessageDialog(this,"Nome: "   + dados.get(0)    + "\n"
                                          +"Idade: "      + dados.get(1)    + "\n"
                                          +"Telefone: "   + dados.get(2)    + "\n"
                                          +"Cidade: "     + dados.get(3));
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdultoActionPerformed
        // TODO add your handling code here:
        
        FollowDAO fwdao = FabricaDAO.getFollowDAO();
        ArrayList<String> followers = new ArrayList<String>();
        try {
            followers = fwdao.getFollowersCategoria(userform, "Adulto");
            for(String e : followers) {System.out.println(e);}
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdultoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAdulto;
    private javax.swing.JMenuItem btnCategoria;
    private javax.swing.JMenuItem btnDados;
    private javax.swing.JMenuItem btnJovem;
    private javax.swing.JMenuItem btnResponsavel;
    private javax.swing.JMenuItem btnTodosAmigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenu menuConsultarCategoria;
    private javax.swing.JMenuItem menuConsultarTweets;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEscrever;
    private javax.swing.JMenuItem menuRemover;
    private javax.swing.JMenuItem menuTweet;
    // End of variables declaration//GEN-END:variables
}
